### ISSUE TITLE
Requestの省略可能な引数の書き方が複数あることについて

### ISSUE THREAD

**Issue by cxxxr** [pokepay/partner-php-sdk#2]
https://github.com/pokepay/partner-php-sdk/blob/master/lib/Request/CreateOrganization.php
https://github.com/pokepay/partner-php-sdk/blob/master/lib/Request/CreateTransaction.php

上の二つのクラスを見ると省略できる引数の書き方を連想配列で渡される場合と
平坦に渡される場合の二通りあるようです
openapiからソースコードを出力する場合、曖昧さを無くすためにどちらかに統一する必要がありました
連想配列で渡す方が順番を考慮しなくていいかと思いますがどうですか

**Comment by fukamachi** [comment]
そうですね。特に異論はないです。

2019年9月6日(金) 19:37 cxxxr <notifications@github.com>:

**Comment by cxxxr** [comment]
ドキュメント整備後にpr出します
